Makie.set_theme!(Makie.theme_dark())
BonitoBook.monaco_theme!("vs-dark")
Styles(
    CSS("li p", "display" => "inline"),
    CSS("body", "background-color" => "black"),
    CSS(
        "@media print",
        CSS(
            "*",
            "-webkit-print-color-adjust" => "exact !important",
            "print-color-adjust" => "exact !important",
            "color-adjust" => "exact !important",
            "filter" => "none !important"
        )
    ),
    CSS(
        ".quick-input-widget",
        "position" => "fixed !important",
        "top" => "10px !important",
    ),
    CSS(
        ".find-widget",
        "position" => "fixed !important",
        "top" => "10px !important",
    ),
    CSS(
        ".monaco-list",
        "max-height" => "60vh !important",
        "overflow-y" => "auto !important"
    ),
    CSS(
        ".cell-editor",
        "width" => "80ch",
        "position" => "relative",
        "display" => "inline-block",
        "padding" => "10px",
        "margin" => "10px",
        "border-radius" => "10px",
        "box-shadow" => "0 4px 8px rgba(0.0, 0.0, 0.0, 0.2)",
        "background-color" => "#1e1e1e",
        "color" => "#d4d4d4"
    ),
    CSS(
        ".monaco-editor-div",
        "background-color" => "transparent",
        "padding" => "0px",
        "margin" => "0px",
    ),
    CSS(".chat.monaco-editor-div",
        "border-radius" => "1px",
        "border" => "1px solid #444",
        "padding" => "2px",
    ),
    CSS(
        ".logging-pre",
        "opacity" => "0",
        "max-height" => "0",
        "overflow" => "hidden",
        "margin" => "0",
        "padding" => "0",
        "line-height" => "0",
        "transition" => "opacity 2s ease, max-height 2s ease",
        "display" => "none"
    ),
    CSS(
        ".logging-pre.show",
        "opacity" => "1",
        "max-height" => "500px",
        "line-height" => "inherit",
        "display" => "block"
    ),
    CSS(".hover-buttons",
        "position" => "absolute",
        "right" => "10px",
        "top" => "0px",
        "z-index" => 1000,
        "opacity" => 0.0,
        "pointer-events" => "none",
    ),
    CSS(".cell-output",
        "padding" => "10px 0px 0px 10px",
    ),
    CSS(".cell-output",
        "width" => "100%",
    ),
    CSS(".small-menu-bar",
        "border" => "1px solid rgba(255, 255, 255, 0.1)",
        "border-radius" => "8px",
        "box-shadow" => "0px 4px 10px rgba(255, 255, 255, 0.15)",
        "padding" => "5px",
        "background" => "#333"
    ),
    CSS(".hide-vertical",
        "opacity" => "0",
        "padding" => "0px",
        "margin" => "0px",
        "height" => "0px",
        "max-height" => "0",
        "overflow" => "hidden",
        "transition" => "max-height 0.1s ease-out"
    ),
    CSS(".show-vertical",
        "max-height" => "1000px",
        "transition" => "max-height 0.1s ease-in"
    ),
    CSS(".hide-horizontal",
        "opacity" => "0",
        "padding" => "0px",
        "margin" => "0px",
        "width" => "0px",
        "max-width" => "0px",
        "overflow" => "hidden",
        "transition" => "max-width 0.1s ease-out",
        "border-radius" => "0px",
    ),
    CSS(".show-horizontal",
        "max-width" => "1000px",
        "transition" => "max-width 0.1s ease-in"
    ),
    CSS(
        ".loading-cell",
        "background" => "rgba(30, 30, 30, 1)",
        "box-shadow" => "0 0 5px rgba(255, 255, 255, 0.1)",
        "animation" => "background-fade 1.5s ease-in-out infinite, shadow-pulse 1.5s ease-in-out infinite",
    ),
    CSS(
        "@keyframes background-fade",
        CSS("0%", "background" => "rgba(30, 30, 30, 1)"),
        CSS("100%", "background" => "rgba(25, 25, 25, 1)"),
    ),
    CSS(
        "@keyframes shadow-pulse",
        CSS("0%", "box-shadow" => "0 0 5px rgba(255, 255, 255, 0.1)"),
        CSS("50%", "box-shadow" => "0 0 15px rgba(255, 255, 255, 0.3)"),
        CSS("100%", "box-shadow" => "0 0 5px rgba(255, 255, 255, 0.1)"),
    ),
    CSS(".julia-dots",
        "background-image" => BonitoBook.assets("julia-dots.svg"),
        "background-size" => "60% auto",
        "background-repeat" => "no-repeat",
        "background-position" => "center",
        "padding-top" => "0.1rem",
        "padding-bottom" => "0.1rem",
        "width" => "1.2rem",
        "height" => "1.2rem",
    ),
    CSS(".small-button",
        "font-weight" => 600,
        "background-color" => "transparent",
        "font-size" => "1rem",
        "min-width" => "1.5rem",
        "padding-left" => "0.3rem",
        "padding-right" => "0.3rem",
        "padding-top" => "0.1rem",
        "padding-bottom" => "0.1rem",
        "border" => "none",
        "border-radius" => "100px",
        "color" => "#bbb",
        "cursor" => "pointer",
        "margin" => "0.25rem",
        "box-shadow" => "0 2px 4px rgba(255, 255, 255, 0.2)",
        "transition" => "background-color 0.2s",
    ),
    CSS(
        ".small-button:hover",
        "background-color" => "#555",
    ),
    CSS(".toggled",
        "color" => "#fff",
        "border" => "none",
        "filter" => "grayscale(100%)",
        "opacity" => "0.5",
        "box-shadow" => "inset 2px 2px 5px rgba(255, 255, 255, 0.5)",
    ),
    CSS(".file-editor-path",
        "font-family" => "'Inter', 'Roboto', 'Arial', sans-serif",
        "font-size" => "14px",
        "font-weight" => "500",
        "color" => "#aaa",
        "letter-spacing" => "0.3px",
        "padding" => "5px 10px",
        "margin" => "1px",
        "width" => "fit-content",
        "border-radius" => "6px",
        "border" => "1px solid rgba(255, 255, 255, 0.1)",
        "box-shadow" => "0px 2px 5px rgba(255, 255, 255, 0.1)",
        "white-space" => "nowrap",
        "overflow" => "hidden",
        "text-overflow" => "ellipsis",
    ),
    CSS(".file-editor",
        "padding" => "0px",
        "margin" => "0px",
        "width" => "90ch",
        "max-height" => "80vh",
    ),
    CSS(".flex-row",
        "display" => "flex",
        "flex-direction" => "row"
    ),
    CSS(".flex-column",
        "display" => "flex",
        "flex-direction" => "column"
    ),
    CSS(".center-content",
        "justify-content" => "center",
        "align-items" => "center"
    ),
    CSS(".inline-block",
        "display" => "inline-block"
    ),
    CSS(".fit-content",
        "width" => "fit-content"
    ),
    CSS(".max-width-90ch",
        "max-width" => "90ch"
    ),
    CSS(".gap-10",
        "gap" => "10px"
    ),
    CSS(".full-width",
        "width" => "100%"
    ),
    CSS(".markdown-body",
        "-ms-text-size-adjust" => "100%",
        "-webkit-text-size-adjust" => "100%",
        "color" => "#d4d4d4",
        "line-height" => "1.5",
        "font-family" => "-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol",
        "font-size" => "16px",
        "word-wrap" => "break-word"
    ),
    CSS(".markdown-body .octicon",
        "display" => "inline-block",
        "fill" => "currentColor",
        "vertical-align" => "text-bottom"
    ),
    CSS(".markdown-body .anchor",
        "float" => "left",
        "line-height" => "1",
        "margin-left" => "-20px",
        "padding-right" => "4px"
    ),
    CSS(".markdown-body .anchor:focus", "outline" => "none"),
    CSS(".markdown-body h1, .markdown-body h2, .markdown-body h3, .markdown-body h4, .markdown-body h5, .markdown-body h6",
        "margin-bottom" => "0", "margin-top" => "0"),
    CSS(".markdown-body h1", "font-size" => "32px", "font-weight" => "600"),
    CSS(".markdown-body h2", "font-size" => "24px", "font-weight" => "600"),
    CSS(".markdown-body h3", "font-size" => "20px", "font-weight" => "600"),
    CSS(".markdown-body h4", "font-size" => "16px", "font-weight" => "600"),
    CSS(".markdown-body h5", "font-size" => "14px", "font-weight" => "600"),
    CSS(".markdown-body h6", "font-size" => "12px", "font-weight" => "600"),
    CSS(".markdown-body a", "color" => "#4f8cd1", "text-decoration" => "none"),
    CSS(".markdown-body a:hover", "text-decoration" => "underline"),
    CSS(".markdown-body strong", "font-weight" => "600"),
    CSS(".markdown-body hr",
        "background" => "transparent",
        "border" => "0",
        "border-bottom" => "1px solid #444",
        "height" => "0",
        "margin" => "15px 0",
        "overflow" => "hidden"
    ),
    CSS(".markdown-body table",
        "border-collapse" => "collapse",
        "border-spacing" => "0"
    ),
    CSS(".markdown-body td, .markdown-body th", "padding" => "0"),
    CSS(".markdown-body blockquote",
        "border-left" => ".25em solid #444",
        "color" => "#9a9a9a",
        "padding" => "0 1em"
    ),
    CSS(".markdown-body code, .markdown-body pre",
        "font-family" => "SFMono-Regular,Consolas,Liberation Mono,Menlo,Courier,monospace",
        "font-size" => "12px"
    ),
    CSS(".markdown-body pre", "margin-bottom" => "0", "margin-top" => "0"),
    CSS(".markdown-body img", "border-style" => "none"),
    CSS(".markdown-body input", "font" => "inherit", "overflow" => "visible"),
    CSS(".markdown-body *", "box-sizing" => "border-box")
)
